{% set name = "openmetadata-sqllineage" %}
{% set version = "1.1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openmetadata-sqllineage-{{ version }}.tar.gz
  sha256: 4dc63ee2f5c241d985e66c96eae93997cfd2dc360159abf3a0279324ce8e770b

build:
  entry_points:
    - sqllineage = sqllineage.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - sqlparse ==0.4.3
    - networkx >=2.4
    - sqlfluff ==2.0.2

test:
  imports:
    - sqllineage
  commands:
    - pip check
    - sqllineage --help
  requires:
    - pip

about:
  home: https://github.com/open-metadata/openmetadata-sqllineage
  summary: OpenMetadata SQL Lineage for Analysis Tool powered by Python and sqlfluff based on sqllineage.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
