{% set name = "openmetadata-sqllineage" %}
{% set version = "1.1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openmetadata-sqllineage-{{ version }}.tar.gz
  sha256: b5a2b57abde448c7d31578c8b0015a5de556bf14465ec9ee8b9a34716d916b89

build:
  entry_points:
    - sqllineage = sqllineage.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - sqlparse >=0.4.3
    - networkx >=2.4
    - sqlfluff >=2.1.2

test:
  imports:
    - sqllineage
  commands:
    - sqllineage --help
  requires:
    - pip

about:
  home: https://github.com/open-metadata/openmetadata-sqllineage
  summary: OpenMetadata SQL Lineage for Analysis Tool powered by Python and sqlfluff based on sqllineage.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
