{% set name = "openmetadata-sqllineage" %}
{% set version = "1.1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openmetadata-sqllineage-{{ version }}.tar.gz
  sha256: c9a060e61e555108ddf487e75f3627c8f080b42816c16a6137c2cbb881b7224b

build:
  entry_points:
    - sqllineage = sqllineage.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - sqlparse ==0.4.3
    - networkx >=2.4
    - sqlfluff ==2.0.2

test:
  imports:
    - sqllineage
  commands:
    - pip check
    - sqllineage --help
  requires:
    - pip

about:
  home: https://github.com/open-metadata/openmetadata-sqllineage
  summary: OpenMetadata SQL Lineage for Analysis Tool powered by Python and sqlfluff based on sqllineage.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
